---
# COPY and this file to secrets.yml and modify as needed
development:
  SECURE_SCHEME: HTTP
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: uIlZs0Q1+/KuRWRp1HdiLeqSx62WBTZ7aIzgfSnk9r0=
  DATABASE_URL: sqlite://db/local/development.db
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  MJ_APIKEY_PUBLIC: <Enter your API Key here>
  MJ_APIKEY_PRIVATE: <Enter you API Secret here>
  MJ_API_URL: https://api.mailjet.com/v3.1/send
  MJ_FROM_EMAIL: <Enter your sender email address here>
  GITHUB_ACCOUNT_URL: https://api.github.com/user

test:
  SECURE_SCHEME: HTTP
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: uIlZs0Q1+/KuRWRp1HdiLeqSx62WBTZ7aIzgfSnk9r0=
  DATABASE_URL: sqlite://db/local/test.db
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  MJ_APIKEY_PUBLIC: <Enter your API Key here>
  MJ_APIKEY_PRIVATE: <Enter you API Secret here>
  MJ_API_URL: https://api.mailjet.com/v3.1/send
  MJ_FROM_EMAIL: <Enter your sender email address here>
  GITHUB_ACCOUNT_URL: https://api.github.com/user

production:
  SECURE_SCHEME: HTTPS
  MSG_KEY: <`rake newkey:msg`>
  DB_KEY: <`rake newkey:db`>
  DATABASE_URL: <do not edit - allow service provider to set>
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  MJ_APIKEY_PUBLIC: <Enter your API Key here>
  MJ_APIKEY_PRIVATE: <Enter you API Secret here>
  MJ_API_URL: https://api.mailjet.com/v3.1/send
  MJ_FROM_EMAIL: <Enter your sender email address here>
  GITHUB_ACCOUNT_URL: https://api.github.com/user
